"""create_workers_table

Revision ID: 4e00dcb4a03e
Revises: 
Create Date: 2025-12-23 21:31:29.445249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e00dcb4a03e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('worker_id', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('STARTING', 'ACTIVE', 'STALE', 'STOPPING', 'STOPPED', name='workerstatus'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=False),
    sa.Column('current_job_count', sa.Integer(), nullable=False),
    sa.Column('total_jobs_processed', sa.Integer(), nullable=False),
    sa.Column('total_jobs_succeeded', sa.Integer(), nullable=False),
    sa.Column('total_jobs_failed', sa.Integer(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('memory_percent', sa.Float(), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('worker_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('current_job_count <= max_concurrent_jobs', name='check_current_job_count_not_exceed_max'),
    sa.CheckConstraint('current_job_count >= 0', name='check_current_job_count_non_negative'),
    sa.CheckConstraint('max_concurrent_jobs > 0', name='check_max_concurrent_jobs_positive'),
    sa.CheckConstraint('stopped_at IS NULL OR started_at IS NULL OR stopped_at >= started_at', name='check_stopped_after_started'),
    sa.CheckConstraint('total_jobs_failed >= 0', name='check_total_jobs_failed_non_negative'),
    sa.CheckConstraint('total_jobs_processed >= 0', name='check_total_jobs_processed_non_negative'),
    sa.CheckConstraint('total_jobs_succeeded >= 0', name='check_total_jobs_succeeded_non_negative'),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_index('idx_workers_hostname_pid', 'workers', ['hostname', 'pid'], unique=False)
    op.create_index('idx_workers_status_heartbeat', 'workers', ['status', 'last_heartbeat_at'], unique=False)
    op.create_index(op.f('ix_workers_current_job_count'), 'workers', ['current_job_count'], unique=False)
    op.create_index(op.f('ix_workers_hostname'), 'workers', ['hostname'], unique=False)
    op.create_index(op.f('ix_workers_last_heartbeat_at'), 'workers', ['last_heartbeat_at'], unique=False)
    op.create_index(op.f('ix_workers_status'), 'workers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workers_status'), table_name='workers')
    op.drop_index(op.f('ix_workers_last_heartbeat_at'), table_name='workers')
    op.drop_index(op.f('ix_workers_hostname'), table_name='workers')
    op.drop_index(op.f('ix_workers_current_job_count'), table_name='workers')
    op.drop_index('idx_workers_status_heartbeat', table_name='workers')
    op.drop_index('idx_workers_hostname_pid', table_name='workers')
    op.drop_table('workers')
    # ### end Alembic commands ###
