"""Initial schema

Revision ID: c5fcef6d02f2
Revises: 
Create Date: 2025-12-23 16:53:28.347877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5fcef6d02f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_policy', sa.Enum('fixed', 'exponential', 'jitter', name='retrypolicy'), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'RUNNING', 'SUCCESS', 'FAILED', 'RETRYING', 'DEAD', 'CANCELED', name='jobstatus'), nullable=False),
    sa.Column('parent_job_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name='check_completed_after_started'),
    sa.CheckConstraint('max_retries >= 0', name='check_max_retries_non_negative'),
    sa.CheckConstraint('priority >= 0 AND priority <= 10', name='check_priority_range'),
    sa.CheckConstraint('retry_count <= max_retries', name='check_retry_count_not_exceed_max'),
    sa.CheckConstraint('retry_count >= 0', name='check_retry_count_non_negative'),
    sa.CheckConstraint('timeout_seconds IS NULL OR timeout_seconds > 0', name='check_timeout_positive'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('idx_jobs_created_at_desc', 'jobs', ['created_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_jobs_status_scheduled_at', 'jobs', ['status', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_jobs_parent_job_id'), 'jobs', ['parent_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_priority'), 'jobs', ['priority'], unique=False)
    op.create_index(op.f('ix_jobs_scheduled_at'), 'jobs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('workflows',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    op.create_index(op.f('ix_workflows_name'), 'workflows', ['name'], unique=True)
    op.create_table('job_dependencies',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_job_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('job_id', 'depends_on_job_id')
    )
    op.create_table('workflow_jobs',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], ),
    sa.PrimaryKeyConstraint('workflow_id', 'job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_jobs')
    op.drop_table('job_dependencies')
    op.drop_index(op.f('ix_workflows_name'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_scheduled_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_priority'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_parent_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_index('idx_jobs_status_scheduled_at', table_name='jobs')
    op.drop_index('idx_jobs_created_at_desc', table_name='jobs', postgresql_using='btree')
    op.drop_table('jobs')
    # ### end Alembic commands ###
